#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path


FUNCTION_RE = re.compile(
    r"function\s+([A-Za-z0-9_]+)\s*\((.*?)\)\s*([^;{]*)[;{]",
    re.DOTALL,
)
EXPORT_HOOK_RE = re.compile(
    r"export\s+(?:const|function)\s+(use[A-Za-z0-9_]+)\s*(?:=|\()",
    re.MULTILINE,
)
FUNCTION_NAME_RE = re.compile(r"functionName:\s*'([A-Za-z0-9_]+)'")
READ_CALL_RE = re.compile(r"\buseReadContracts?\b")
CREATE_VIEW_RE = re.compile(r"CREATE VIEW\s+([A-Za-z0-9_]+)\s+AS", re.IGNORECASE)
CREATE_TABLE_RE = re.compile(
    r"CREATE TABLE IF NOT EXISTS\s+([A-Za-z0-9_]+)", re.IGNORECASE
)


VIEWER_SPECS = (
    ("LOVE20RoundViewer", "useLOVE20RoundViewer.ts"),
    ("LOVE20TokenViewer", "useLOVE20TokenViewer.ts"),
    ("LOVE20MintViewer", "useLOVE20MintViewer.ts"),
)


def collapse_ws(value: str) -> str:
    return " ".join(value.replace("\n", " ").split())


def parse_read_functions(content: str) -> list[dict[str, str]]:
    functions: list[dict[str, str]] = []
    for match in FUNCTION_RE.finditer(content):
        name, args, trailer = match.groups()
        if not re.search(r"\b(view|pure)\b", trailer):
            continue
        if name.startswith("_"):
            continue
        functions.append({"name": name, "args": collapse_ws(args)})
    return functions


def parse_hook_blocks(content: str) -> list[dict[str, object]]:
    matches = list(EXPORT_HOOK_RE.finditer(content))
    hooks: list[dict[str, object]] = []
    for index, match in enumerate(matches):
        hook_name = match.group(1)
        start = match.start()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        block = content[start:end]
        function_names = []
        seen = set()
        for function_name in FUNCTION_NAME_RE.findall(block):
            if function_name in seen:
                continue
            seen.add(function_name)
            function_names.append(function_name)
        hooks.append({"hook": hook_name, "function_names": function_names})
    return hooks


def format_signature(function: dict[str, str]) -> str:
    args = function["args"]
    if args:
        return f'{function["name"]}({args})'
    return f'{function["name"]}()'


def render_header() -> str:
    return "\n".join(
        [
            "# Generated State and Event Index",
            "",
            "This file is generated by `ai/skills/love20-state-and-events/scripts/generate_state_event_index.py`.",
            "Regenerate it after updating LOVE20 viewer contracts, core or extension hooks, or log SQL surfaces.",
            "",
        ]
    )


def resolve_repo(repo_parent: Path, canonical_name: str) -> Path:
    candidates = [canonical_name, f"LOVE20-{canonical_name}"]
    for candidate in candidates:
        path = repo_parent / candidate
        if path.exists():
            return path
    raise FileNotFoundError(
        f"Could not locate repo '{canonical_name}' or 'LOVE20-{canonical_name}' under {repo_parent}"
    )


def workspace_path(path: Path, docs_root: Path) -> str:
    resolved = path.resolve()
    try:
        return f"docs/{resolved.relative_to(docs_root.resolve())}"
    except ValueError:
        display_names = {
            "docs": ["docs", "docs"],
            "core": ["core", "core"],
            "periphery": ["periphery", "periphery"],
            "script": ["script", "script"],
            "interface": ["interface", "interface"],
            "extension": ["extension", "extension"],
            "extension-group": ["extension-group", "extension-group"],
            "extension-lp": ["extension-lp", "extension-lp"],
            "group": ["group", "group"],
        }
        for display_name, aliases in display_names.items():
            for alias in aliases:
                repo_root = docs_root.parent / alias
                if not repo_root.is_dir():
                    continue
                try:
                    return f"{display_name}/{resolved.relative_to(repo_root.resolve())}"
                except ValueError:
                    continue
        return str(resolved)


def render_viewer_section(
    contract_path: Path, hook_path: Path, docs_root: Path
) -> str:
    read_functions = parse_read_functions(contract_path.read_text())
    hook_blocks = parse_hook_blocks(hook_path.read_text())
    hooks_by_function: dict[str, list[str]] = {}
    for block in hook_blocks:
        hook_name = block["hook"]
        for function_name in block["function_names"]:
            hooks_by_function.setdefault(function_name, []).append(hook_name)

    lines = [f"## {contract_path.stem}", ""]
    lines.append(f"- Contract: `{workspace_path(contract_path, docs_root)}`")
    lines.append(f"- Hook file: `{workspace_path(hook_path, docs_root)}`")
    lines.append(f"- Read functions: {len(read_functions)}")
    lines.append(f"- Exported hooks: {len(hook_blocks)}")
    lines.append("")
    lines.append("| Function | Signature | Direct hooks |")
    lines.append("| --- | --- | --- |")
    for function in read_functions:
        hook_names = ", ".join(f"`{name}`" for name in hooks_by_function.get(function["name"], []))
        if not hook_names:
            hook_names = "-"
        lines.append(
            f"| `{function['name']}` | `{format_signature(function)}` | {hook_names} |"
        )
    return "\n".join(lines)


def render_hook_inventory_section(
    title: str, hook_files: list[Path], docs_root: Path
) -> str:
    lines = [title, "", "| Hook | File | Contract functions used |", "| --- | --- | --- |"]
    found = False

    for path in hook_files:
        content = path.read_text()
        if not READ_CALL_RE.search(content):
            continue
        for block in parse_hook_blocks(content):
            function_names = block["function_names"]
            if not function_names:
                continue
            found = True
            fn_text = ", ".join(f"`{name}`" for name in function_names)
            lines.append(
                f"| `{block['hook']}` | `{workspace_path(path, docs_root)}` | {fn_text} |"
            )

    if not found:
        lines.append("| - | - | - |")

    lines.append("")
    return "\n".join(lines)


def render_sql_section(
    table_sql_path: Path, view_sql_path: Path, stat_dir: Path, docs_root: Path
) -> str:
    table_names = CREATE_TABLE_RE.findall(table_sql_path.read_text())
    view_names = CREATE_VIEW_RE.findall(view_sql_path.read_text())
    stat_files = sorted(stat_dir.glob("*.sql"))

    lines = ["## Indexed SQL surfaces", ""]
    lines.append(f"- Tables file: `{workspace_path(table_sql_path, docs_root)}`")
    lines.append(f"- Views file: `{workspace_path(view_sql_path, docs_root)}`")
    lines.append("")
    lines.append("### Tables")
    lines.append("")
    for name in table_names:
        lines.append(f"- `{name}`")
    lines.append("")
    lines.append("### Views")
    lines.append("")
    for name in view_names:
        lines.append(f"- `{name}`")
    lines.append("")
    lines.append("### Stat queries")
    lines.append("")
    for path in stat_files:
        lines.append(f"- `{workspace_path(path, docs_root)}`")
    return "\n".join(lines)


def main() -> None:
    docs_root = Path(__file__).resolve().parents[4]
    repo_parent = docs_root.parent
    periphery_root = resolve_repo(repo_parent, "periphery")
    interface_root = resolve_repo(repo_parent, "interface")
    script_root = resolve_repo(repo_parent, "script")
    hooks_root = interface_root / "src" / "hooks"
    composite_dir = interface_root / "src" / "hooks" / "composite"
    core_contract_dir = hooks_root / "contracts"
    extension_root = hooks_root / "extension"
    output_path = (
        docs_root
        / "ai"
        / "skills"
        / "love20-state-and-events"
        / "references"
        / "generated-state-event-index.md"
    )

    sections = [render_header()]

    sections.append(
        render_hook_inventory_section(
            "## Frontend core contract read hooks",
            sorted(core_contract_dir.rglob("*.ts")),
            docs_root,
        )
    )
    sections.append(
        render_hook_inventory_section(
            "## Frontend core composite read hooks",
            sorted(composite_dir.rglob("*.ts")),
            docs_root,
        )
    )
    sections.append(
        render_hook_inventory_section(
            "## Frontend extension contract read hooks",
            sorted(
                path
                for path in extension_root.rglob("*.ts")
                if "contracts" in path.parts
            ),
            docs_root,
        )
    )
    sections.append(
        render_hook_inventory_section(
            "## Frontend extension composite read hooks",
            sorted(
                path
                for path in extension_root.rglob("*.ts")
                if "composite" in path.parts
            ),
            docs_root,
        )
    )

    for contract_name, hook_file_name in VIEWER_SPECS:
        contract_path = periphery_root / "src" / f"{contract_name}.sol"
        hook_path = interface_root / "src" / "hooks" / "contracts" / hook_file_name
        sections.append(render_viewer_section(contract_path, hook_path, docs_root))

    sql_section = render_sql_section(
        script_root / "script" / "log" / "sql" / "init" / "01_tables.sql",
        script_root / "script" / "log" / "sql" / "init" / "02_views.sql",
        script_root / "script" / "log" / "sql" / "stat",
        docs_root,
    )
    sections.append(sql_section)

    output_path.write_text("\n\n".join(sections) + "\n")


if __name__ == "__main__":
    main()
