#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path


FUNCTION_RE = re.compile(
    r"function\s+([A-Za-z0-9_]+)\s*\((.*?)\)\s*([^;{]*)[;{]",
    re.DOTALL,
)


def collapse_ws(value: str) -> str:
    return " ".join(value.replace("\n", " ").split())


def parse_functions(content: str) -> list[dict[str, str]]:
    functions: list[dict[str, str]] = []
    for match in FUNCTION_RE.finditer(content):
        name, args, trailer = match.groups()
        kind = "read" if re.search(r"\b(view|pure)\b", trailer) else "write"
        functions.append(
            {
                "name": name,
                "args": collapse_ws(args),
                "kind": kind,
            }
        )
    return functions


def format_signature(function: dict[str, str]) -> str:
    args = function["args"]
    if args:
        return f'{function["name"]}({args})'
    return f'{function["name"]}()'


def resolve_repo(repo_parent: Path, canonical_name: str) -> Path:
    candidates = [canonical_name, f"LOVE20-{canonical_name}"]
    for candidate in candidates:
        path = repo_parent / candidate
        if path.exists():
            return path
    raise FileNotFoundError(
        f"Could not locate repo '{canonical_name}' or 'LOVE20-{canonical_name}' under {repo_parent}"
    )


def repo_path(path: Path, repo_root: Path, display_name: str) -> str:
    resolved = path.resolve()
    try:
        return f"{display_name}/{resolved.relative_to(repo_root.resolve())}"
    except ValueError:
        return str(resolved)


def implementation_path(interface_path: Path, core_src_dir: Path) -> Path | None:
    stem = interface_path.stem
    if stem == "IPhase":
        candidate = core_src_dir / "Phase.sol"
    elif stem.startswith("I"):
        candidate = core_src_dir / f"{stem[1:]}.sol"
    else:
        return None
    return candidate if candidate.exists() else None


def render_section(interface_path: Path, core_src_dir: Path, core_root: Path) -> str:
    content = interface_path.read_text()
    functions = parse_functions(content)
    reads = [item for item in functions if item["kind"] == "read"]
    writes = [item for item in functions if item["kind"] == "write"]
    implementation = implementation_path(interface_path, core_src_dir)

    lines = [f"## {interface_path.stem}", ""]
    lines.append(f"- Interface: `{repo_path(interface_path, core_root, 'core')}`")
    if implementation is not None:
        lines.append(f"- Implementation: `{repo_path(implementation, core_root, 'core')}`")
    lines.append(f"- Read functions: {len(reads)}")
    lines.append(f"- Write functions: {len(writes)}")
    lines.append("")

    if reads:
        lines.append("### Reads")
        lines.append("")
        for function in reads:
            lines.append(f"- `{format_signature(function)}`")
        lines.append("")

    if writes:
        lines.append("### Writes")
        lines.append("")
        for function in writes:
            lines.append(f"- `{format_signature(function)}`")
        lines.append("")

    return "\n".join(lines).rstrip()


def main() -> None:
    docs_root = Path(__file__).resolve().parents[4]
    core_root = resolve_repo(docs_root.parent, "core")
    interfaces_dir = core_root / "src" / "interfaces"
    core_src_dir = core_root / "src"
    output_path = docs_root / "ai" / "skills" / "love20-core-protocol" / "references" / "generated-interface-index.md"

    interface_paths = sorted(interfaces_dir.glob("ILOVE20*.sol"))
    phase_interface = interfaces_dir / "IPhase.sol"
    if phase_interface.exists():
        interface_paths.append(phase_interface)

    sections = [render_section(path, core_src_dir, core_root) for path in interface_paths]

    header = [
        "# Generated Interface Index",
        "",
        "This file is generated by `ai/skills/love20-core-protocol/scripts/generate_interface_index.py`.",
        "Regenerate it after updating LOVE20 core interfaces.",
        "",
    ]

    output_path.write_text("\n".join(header) + "\n" + "\n\n".join(sections) + "\n")


if __name__ == "__main__":
    main()
